version: 0.2

env:
  variables:
    DOCKER_USERNAME: "akamusaib"
  secrets-manager:
    DOCKER_PASSWORD: "keyvalue:keyname"

phases:
  install:
    commands:
      - echo enter the installed phase
      - apt-get update -y

  pre_build:
    - echo enter the build phase
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD


  build:
    - echo enter the build phase
    - docker build -t mystock:v3 .
    - docker tag mystock:v3  akamusaib/repo-dump:mystock:v3

  post-build:
    commands:
      - echo Build finished 'date'
      - echo Pushing the docker image...
      - docker push akamusaib/repo-dump:mystock:v2
      
