version: 0.2

env:
  variables:
    DOCKER_USERNAME: "akamusaib"
  secrets-manager:
    DOCKER_PASSWORD: "dockerpass:DOCKERPASS"

phases:
  pre_build:
    commands:
    - echo enter the build phase
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
    - echo enter the build phase
    - docker build -t mystock:v3 .
    - docker tag mystock:v3  akamusaib/repo-dump:mystock:v3
  post_build:
    commands:
      - echo Build finished 'date'
      - echo Pushing the docker image...
      - docker push akamusaib/repo-dump:mystock:v2
      
